[cpe1]
VPPSrcIface = 1
IsSubIf = false
HasQinQ = false
OuterVLAN = 0
InnerVLAN = 0
MTU = 1500
FlexId = "cpe1"

[cpe2]
VPPSrcIface = 2
IsSubIf = false
HasQinQ = false
OuterVLAN = 0
InnerVLAN = 0
MTU = 1500
FlexId = "cpe2"